### Variables
@baseUrl = http://localhost:3000
@contentType = application/json


# health check
GET {{baseUrl}}


### todo -- 


### order add api
POST {{baseUrl}}/api/order/place
Content-Type: {{contentType}}

{
  "userId": "6a72e76134a85d2ce710053e",
  "delivery": {
    "name": "John",
    "phone": "9876543210",
    "address": "ABC Street"
  },
  "items": [
    {
      "menuItemId": "6a72e76134a85d2ce7100551",
      "quantity": 2
    },
    {
      "menuItemId": "6a72e76134a85d2ce7100552",
      "quantity": 1
    }
  ]
}

### get orders
GET {{baseUrl}}/api/order/6a72e76134a85d2ce710053e


### get order details
GET {{baseUrl}}/api/order/details/6a731cfc5bd11111f7e08d49

### change order status
PUT {{baseUrl}}/api/order/6a72fd560cf30dd0411746cb
Content-Type: application/json

{
  "status": "OUT_FOR_DELIVERY"
}




### menu listing api
GET {{baseUrl}}/api/menu/list?page=1&limit=10